steps:
  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: https://registry.lajas.tech/v2/
      repo: registry.lajas.tech/minecraft-spectrum-sync
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_token
    when:
      branch: main
      event:
        - push
        - cron
      cron: "Rebuild"
